# Generated by Django 3.0.5 on 2020-04-14 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
