# Generated by Django 3.0.5 on 2020-04-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200414_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='first_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='last_name',
            field=models.CharField(default='k', max_length=200),
            preserve_default=False,
        ),
    ]
